### ISSUE TITLE
Play a video larger than 4GB

### ISSUE THREAD

**Issue by snowinszu** [feross/render-media#28] opened 2017-08-17 08:49 UTC
I tried to play a MP4 video larger than 3GB, but it doesn't work.
![wechatimg1086](https://user-images.githubusercontent.com/14010277/29403791-f59d2682-836b-11e7-9fe6-313347fab78e.jpeg)

**Comment by snowinszu** [comment] 2017-08-22 02:49
sorry, 4GB, not 3GB

**Comment by r3k2** [comment] 2018-02-09 00:19
@snowinszu @feross I am having the same issue using peertube,  some of my videos are over 4G and I can't make smaller... the type of shows we do are 1-2 hours long each month... is there any work around? or if someone gives me a magic trick to reduce half the size with out loosing obvios quality i'm open to suggestions. thanks

**Comment by feross** [comment] 2018-02-16 22:02
It's not clear why 4GB is a magic number for render-media. We don't hardcode that anywhere.

**Comment by Cheedoong** [comment] 2018-02-17 05:34
Maybe, because of some hidden range or size limit? (e.g., uint32_t for representing a file, blob, or stream size?) 

Another possible reason: the memory allocation and management mechanisms of the browser may also cause some trouble.

**Comment by feross** [comment] 2018-04-15 07:41
What browser are you using? I just tested an MP4 file greater than 4 GB in Chrome 65 and it worked perfectly. Closing for now, will re-open if there's more info about the issue, including browser, version, and a sample file that reproduces the issue.

**Closed as completed by feross** 2018-04-15 07:41 UTC
