### ISSUE TITLE
Output appendChild problem

### ISSUE THREAD

**Issue by atmoner** [feross/render-media#23] opened 2017-01-23 20:32 UTC
In this problem, I want use WebTorrent with the example given here: [HTML example with status showing UI](https://github.com/feross/webtorrent/blob/master/docs/get-started.md#html-example-with-status-showing-ui)
I have a little problem with the library 'render-media'

`TypeError: Cannot read property 'appendChild' of null`

![problem](https://cloud.githubusercontent.com/assets/1071490/22221076/b724b9f8-e1b1-11e6-8c0b-410d4fad60cd.png)

This is the only problem I encounter since when I comment on this line:
```
  torrent.files[0].appendTo('#output')
```
All work perfectly 
![problem2](https://cloud.githubusercontent.com/assets/1071490/22221407/3083eb9c-e1b3-11e6-8525-911395402acb.png)

If you have an idea about the problem.
Thanks for your work :+1:

**Comment by feross** [comment] 2017-01-23 22:50
This issue is probably caused by you putting the script in the `<head>` of the page instead of at the very end, right before the closing `</body>` tag.

The code is running and looking for the html element with the ID of "output" and not finding anything.

**Closed as completed by feross** 2017-01-23 22:50 UTC

**Comment by atmoner** [comment] 2017-01-23 23:25
I have done exactly the same as updating your [get-started.md](https://github.com/feross/webtorrent/blob/63015f4cae3cd783e84071dd9b6117c75a7a7933/docs/get-started.md) and I always get the same error!
Moreover it seems to me that the lack require of webtorrent after `<script>` in your [get-started.md](https://github.com/feross/webtorrent/blob/63015f4cae3cd783e84071dd9b6117c75a7a7933/docs/get-started.md)

`var WebTorrent = require('webtorrent')`

I will try with videostream or mediasource (Or if you have any other to advise me)

**Comment by feross** [comment] 2017-01-25 00:16
`var WebTorrent = require('webtorrent')` is not required because the bundled JS version of WebTorrent puts itself on the `window`. Can you link to a complete example of your code?
